### ISSUE TITLE
Adjust to api question naming of radio and checkbox

### ISSUE THREAD

**Issue by sliverc** [projectcaluma/ember-caluma-form-builder#207]
In API following types have been renamed:
RadioQuestion -> ChoiceQuestion
CheckboxQuestion -> MultipleChoiceQuestion

See https://github.com/projectcaluma/caluma/pull/265 for more details also on the reasoning.

Naming of radio and checkbox in the frontend can remain as it is a layout decision the user has to be aware of

**Comment by sliverc** [comment]
@kaldras @czosel once [projectcaluma/caluma#265](https://github.com/projectcaluma/caluma/pull/265) is merged it won't be backwards compatible and this will need to be changed.

Leaving PR open till we know someone has time to adjust it.

**Comment by czosel** [comment]
Fixed in #209
